name: ScientificGames
main: xyz.champrin.scientificgames.ScientificGames
version: "1.5.0"
api: ["1.0.8"]
load: POSTWORLD


author: Champrin,Spiderman
description: "科学游戏"

commands:
  ill:
    permission: Illness.command.ill
    usage: "/ill"
    description: "§e 查看药物列表"
    aliases: []
  rlset:
    usage: "/rlset help"
    permission: Illness.command.cmd
    description: "§b关于§eScientificGames§b的设置"
    aliases: []
permissions:
  illness.ill:
    default: true
  illness.cmd:
    default: op