name: ScientificGames
main: xyz.champrin.ScientificGames
version: "1.0.0"
api: ["1.0.8"]
load: STARTUP

author: Champrin
description: 科学游戏
website: https://champrin.github.io

commands:
  ill:
    permission: illness.command.ill
    usage: "/ill"
    description: "§eScientificGames查看药物列表"
    aliases: []
  rlset:
    usage: "/rlset help"
    permission: illness.command.cmd
    description: "§b关于§eScientificGames§b的设置"
    aliases: []
permissions:
  illness.ill:
    default: true
  illness.cmd:
    default: op